---
# file: create-ip-pools.yaml

- name: Create IP Management Pools
  ucs_ip_pool:
    name: "{{ item.name }}"
    order: "sequential"
    first_addr: "{{ item.first }}"
    last_addr: "{{ item.last }}"
    subnet_mask: "{{ item.netmask }}"
    default_gw: "{{ item.gateway }}"
    primary_dns: "{{ item.dns1 }}"
    secondary_dns: "{{ item.dns2 }}"
    org_dn: "{{ this_ucs_org }}"
    hostname: "{{ this_ucs_hostname }}"
    username: "{{ this_ucs_username }}"
    password: "{{ this_ucs_password }}"
  loop: "{{ demo_ip_pools }}"
