---
# file: create-uuid-pools.yaml

- name: Create UUID Pools
  ucs_uuid_pool:
    name: "{{ item.name }}"
    order: "sequential"
    prefix: "{{ item.prefix }}"
    first_uuid: "{{ item.first }}"
    last_uuid: "{{ item.last }}"
    org_dn: "{{ this_ucs_org }}"
    hostname: "{{ this_ucs_hostname }}"
    username: "{{ this_ucs_username }}"
    password: "{{ this_ucs_password }}"
  loop: "{{ demo_uuid_pools }}"
