---
# file: configure-ntp.yaml

- name: Configure Network Time Protocol
  ucs_ntp_server:
    ntp_server: 0.us.pool.ntp.org
    description: US National Time Server Pool
    state: present
    hostname: "{{ this_ucs_hostname }}"
    username: "{{ this_ucs_username }}"
    password: "{{ this_ucs_password }}"
