---
# file: create-vlans.yaml

- name: Create VMM VLANs (A/B)
  ucs_vlans:
    name: "{{ item.name }}"
    id: "{{ item.id }}"
    fabric: "{{ item.fabric }}"
    state: present
    hostname: "{{ this_ucs_hostname }}"
    username: "{{ this_ucs_username }}"
    password: "{{ this_ucs_password }}"
  loop: "{{ demo_vlans }}"
